import colors from 'vuetify/es5/util/colors'
import {
  mdiHeart, mdiChevronRight, mdiInformationOutline, mdiChevronLeft, mdiCart, mdiMenu, mdiChevronDown, mdiClose, mdiLogout,
  mdiCheckboxMarkedCircle, mdiChartGantt, mdiTableEdit, mdiFoodApple, mdiBarcodeScan, mdiAccountSwitch, mdiGoogleCirclesExtended,
  mdiAccount, mdiMinus, mdiPlus, mdiPencilOutline, mdiCurrencyEur, mdiTrashCanOutline, mdiPlusCircle, mdiMagnify, mdiCloseCircle,
  mdiCircle, mdiPlusThick, mdiCartArrowUp, mdiCartArrowDown, mdiForum, mdiAlarm, mdiFacebook, mdiTwitter, mdiLinkedin, mdiInstagram,
  mdiAccountCircle, mdiLogin, mdiSproutOutline, mdiBarn, mdiMenuUp, mdiCartPlus, mdiAccountTieVoiceOutline, mdiLock, mdiEye, mdiEyeOff,
  mdiCreditCardOutline, mdiCheckCircleOutline, mdiEmail, mdiArrowLeftBoldCircle, mdiArrowRightBoldCircle, mdiHelp, mdiPanoramaFisheye,
  mdiPrinter, mdiCheckCircle, mdiFileDocumentOutline, mdiCheckboxMarked, mdiCashRegister, mdiCheckboxBlankOutline, mdiCheckboxBlankCircleOutline, mdiHome, mdiHistory, mdiHelpCircle, mdiSprout, mdiHeartOutline, mdiClock, mdiAlertOutline, mdiWarehouse, mdiArrowUp, mdiCalendar, mdiTimer, mdiCalendarToday, mdiFormatClear, mdiShieldAlert, mdiFactory, mdiPackageDown, mdiPackageUp
} from '@mdi/js'

export default {
  theme: {
    dark: false,
    themes: {
      dark: {
        primary: colors.blue.darken2,
        accent: colors.grey.darken3,
        secondary: colors.amber.darken3,
        info: colors.teal.lighten1,
        warning: colors.amber.base,
        error: colors.deepOrange.accent4,
        success: colors.green.accent3
      },
      light: {
        primary: '#AECD6B',
        accent: '#316827',
        secondary: '#C40219'
      }
    }
  },
  icons: {
    values: {
      'mdi-help': mdiHelp,
      'mdi-calendar': mdiCalendar,
      'mdi-calendar-today': mdiCalendarToday,
      'mdi-timer': mdiTimer,
      'mdi-checkbox-marked': mdiCheckboxMarked,
      'mdi-checkbox-blank-outline': mdiCheckboxBlankOutline,
      'mdi-heart': mdiHeart,
      'mdi-chevron-right': mdiChevronRight,
      'mdi-chevron-left': mdiChevronLeft,
      'mdi-cart': mdiCart,
      'mdi-menu': mdiMenu,
      'mdi-chevron-down': mdiChevronDown,
      'mdi-close': mdiClose,
      'mdi-logout': mdiLogout,
      'mdi-checkbox-marked-circle': mdiCheckboxMarkedCircle,
      'mdi-checkbox-blank-circle-outline': mdiCheckboxBlankCircleOutline,
      'mdi-chart-gantt': mdiChartGantt,
      'mdi-table-edit': mdiTableEdit,
      'mdi-food-apple': mdiFoodApple,
      'mdi-barcode-scan': mdiBarcodeScan,
      'mdi-account-switch': mdiAccountSwitch,
      'mdi-google-circles-extended': mdiGoogleCirclesExtended,
      'mdi-account': mdiAccount,
      'mdi-home': mdiHome,
      'mdi-history': mdiHistory,
      'mdi-help-circle': mdiHelpCircle,
      'mdi-sprout': mdiSprout,
      'mdi-heart-outline': mdiHeartOutline,
      'mdi-information-outline': mdiInformationOutline,
      'mdi-minus': mdiMinus,
      'mdi-plus': mdiPlus,
      'mdi-pencil-outline': mdiPencilOutline,
      'mdi-currency-eur': mdiCurrencyEur,
      'mdi-trash-can-outline': mdiTrashCanOutline,
      'mdi-plus-circle': mdiPlusCircle,
      'mdi-magnify': mdiMagnify,
      'mdi-close-circle': mdiCloseCircle,
      'mdi-circle': mdiCircle,
      'mdi-plus-thick': mdiPlusThick,
      'mdi-cart-arrow-up': mdiCartArrowUp,
      'mdi-cart-arrow-down': mdiCartArrowDown,
      'mdi-forum': mdiForum,
      'mdi-alarm': mdiAlarm,
      'mdi-facebook': mdiFacebook,
      'mdi-twitter': mdiTwitter,
      'mdi-linkedin': mdiLinkedin,
      'mdi-instagram': mdiInstagram,
      'mdi-account-circle': mdiAccountCircle,
      'mdi-login': mdiLogin,
      'mdi-sprout-outline': mdiSproutOutline,
      'mdi-barn': mdiBarn,
      'mdi-menu-up': mdiMenuUp,
      'mdi-cart-plus': mdiCartPlus,
      'mdi-account-tie-voice-outline': mdiAccountTieVoiceOutline,
      'mdi-lock': mdiLock,
      'mdi-eye': mdiEye,
      'mdi-eye-off': mdiEyeOff,
      'mdi-credit-card-outline': mdiCreditCardOutline,
      'mdi-check-circle': mdiCheckCircle,
      'mdi-check-circle-outline': mdiCheckCircleOutline,
      'mdi-email': mdiEmail,
      'mdi-arrow-left-bold-circle': mdiArrowLeftBoldCircle,
      'mdi-arrow-right-bold-circle': mdiArrowRightBoldCircle,
      'mdi-printer': mdiPrinter,
      'mdi-file-document-outline': mdiFileDocumentOutline,
      'mdi-cash-register': mdiCashRegister,
      'mdi-clock': mdiClock,
      'mdi-alert-outline': mdiAlertOutline,
      'mdi-arrow-up': mdiArrowUp,
      'mdi-clear': mdiFormatClear,
      'mdi-shield-alert': mdiShieldAlert,
      'mdi-Package-Up': mdiPackageUp,
      'mdi-Package-Down': mdiPackageDown,
      'mdi-Factory': mdiFactory,
      'mdi-Warehouse': mdiWarehouse,
      'mdi-panorama-fisheye': mdiPanoramaFisheye
    }
  }
}
